
parameters:
- name: buildConfiguration
  type: string
  default: 'Release'

steps:
  - task: DotNetCoreCLI@2
    displayName: 'Build the project - ${{parameters.buildConfiguration}}'
    inputs:
      command: 'build'
      arguments: '--no-restore --configuration ${{parameters.buildConfiguration}}'
      projects: '**/*.csproj'

  - template: publish.yml
    parameters:
      buildConfiguration: '${{parameters.buildConfiguration}}'
